services:
  - type: web
    name: employee-policy-agent
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn src.api.routes:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: HF_HOME
        value: /tmp/hf_cache
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /tmp/sentence_transformers